"""
GGUF export via llama.cpp's convert_hf_to_gguf.py.

Generates a shell script and instructions since llama.cpp is not bundled.
Optionally invokes the converter if llama_cpp_python is installed.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from moro.core.errors import ExportError


def write_gguf_script(
    merged_model_dir: Path,
    out_dir: Path,
    quantization: str = "q4_k_m",
    project_name: str = "model",
) -> Path:
    """
    Write a shell script that converts the merged model to GGUF using llama.cpp.

    Returns the script path.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    script_content = f"""\
#!/usr/bin/env bash
# MoroAI — GGUF conversion script for {project_name}
# Generated by `moro export --format gguf`
#
# Requirements:
#   git clone https://github.com/ggerganov/llama.cpp
#   cd llama.cpp && make -j4
#   pip install -r requirements/requirements-convert_hf_to_gguf.txt
#
# Usage:
#   chmod +x convert_to_gguf.sh && ./convert_to_gguf.sh

set -euo pipefail

LLAMA_CPP="${{LLAMA_CPP_PATH:-./llama.cpp}}"
MERGED_MODEL="{merged_model_dir.resolve()}"
OUTPUT_DIR="{out_dir.resolve()}"
QUANTIZATION="{quantization}"
MODEL_NAME="{project_name}"

if [ ! -f "$LLAMA_CPP/convert_hf_to_gguf.py" ]; then
  echo "ERROR: llama.cpp not found at $LLAMA_CPP"
  echo "Clone llama.cpp and set LLAMA_CPP_PATH to its location."
  exit 1
fi

echo "→ Converting to F16 GGUF..."
python "$LLAMA_CPP/convert_hf_to_gguf.py" \\
  --outtype f16 \\
  --outfile "$OUTPUT_DIR/${{MODEL_NAME}}-f16.gguf" \\
  "$MERGED_MODEL"

echo "→ Quantizing to $QUANTIZATION..."
"$LLAMA_CPP/llama-quantize" \\
  "$OUTPUT_DIR/${{MODEL_NAME}}-f16.gguf" \\
  "$OUTPUT_DIR/${{MODEL_NAME}}-${{QUANTIZATION}}.gguf" \\
  "$QUANTIZATION"

echo "✓ Done: $OUTPUT_DIR/${{MODEL_NAME}}-${{QUANTIZATION}}.gguf"
echo ""
echo "To run with llama.cpp:"
echo "  $LLAMA_CPP/llama-cli -m $OUTPUT_DIR/${{MODEL_NAME}}-${{QUANTIZATION}}.gguf -i"
echo ""
echo "To run with Ollama:"
echo "  MODEL_FILE: FROM $OUTPUT_DIR/${{MODEL_NAME}}-${{QUANTIZATION}}.gguf"
"""

    script_path = out_dir / "convert_to_gguf.sh"
    script_path.write_text(script_content, encoding="utf-8")
    script_path.chmod(0o755)
    return script_path


def convert_to_gguf_direct(
    merged_model_dir: Path,
    out_dir: Path,
    llama_cpp_path: Path,
    quantization: str = "q4_k_m",
    project_name: str = "model",
) -> Path:
    """
    Directly invoke llama.cpp conversion if llama.cpp is available locally.

    Returns the path to the quantized GGUF file.
    """
    merged_model_dir = Path(merged_model_dir).resolve()
    out_dir = Path(out_dir)
    llama_cpp_path = Path(llama_cpp_path)
    out_dir.mkdir(parents=True, exist_ok=True)

    converter = llama_cpp_path / "convert_hf_to_gguf.py"
    quantizer = llama_cpp_path / "llama-quantize"

    if not converter.exists():
        raise ExportError(f"convert_hf_to_gguf.py not found in: {llama_cpp_path}")
    if not quantizer.exists():
        raise ExportError(f"llama-quantize not found in: {llama_cpp_path}")

    python = shutil.which("python3") or shutil.which("python")
    if not python:
        raise ExportError("Python interpreter not found in PATH.")

    f16_path = out_dir / f"{project_name}-f16.gguf"

    # Step 1: Convert to F16
    subprocess.run(
        [
            python,
            str(converter),
            "--outtype",
            "f16",
            "--outfile",
            str(f16_path),
            str(merged_model_dir),
        ],
        check=True,
    )

    # Step 2: Quantize
    quant_path = out_dir / f"{project_name}-{quantization}.gguf"
    subprocess.run(
        [str(quantizer), str(f16_path), str(quant_path), quantization],
        check=True,
    )

    # Remove intermediate F16 to save disk
    if f16_path.exists() and quant_path.exists():
        f16_path.unlink()

    return quant_path
