"""
MoroAI Production Log Storage Schema.

Defines the SQLite schema for storing production inference logs
and tracking flywheel processing state.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

# Complete DDL for production log database
PRODUCTION_LOG_SCHEMA = """
-- Production inference logs written by gateway/middleware
CREATE TABLE IF NOT EXISTS inference_logs (
    log_id          TEXT PRIMARY KEY,
    session_id      TEXT NOT NULL,
    model_name      TEXT NOT NULL DEFAULT 'production',
    prompt          TEXT NOT NULL,
    completion      TEXT NOT NULL,
    context         TEXT,
    user_rating     REAL,
    human_correction TEXT,
    latency_ms      REAL,
    metadata_json   TEXT DEFAULT '{}',
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),

    -- Flywheel processing state
    is_processed    INTEGER NOT NULL DEFAULT 0,
    processed_at    TEXT,
    epoch_id        TEXT
);

CREATE INDEX IF NOT EXISTS idx_inference_logs_unprocessed
    ON inference_logs (is_processed, created_at);

CREATE INDEX IF NOT EXISTS idx_inference_logs_session
    ON inference_logs (session_id);

CREATE INDEX IF NOT EXISTS idx_inference_logs_epoch
    ON inference_logs (epoch_id);

-- Preference pairs generated by the extractor
CREATE TABLE IF NOT EXISTS preference_pairs (
    pair_id         TEXT PRIMARY KEY,
    source_log_id   TEXT NOT NULL,
    prompt          TEXT NOT NULL,
    chosen          TEXT NOT NULL,
    rejected        TEXT NOT NULL,
    feedback_type   TEXT NOT NULL,
    confidence_delta REAL NOT NULL DEFAULT 0.5,
    metadata_json   TEXT DEFAULT '{}',
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    epoch_id        TEXT
);

CREATE INDEX IF NOT EXISTS idx_preference_pairs_epoch
    ON preference_pairs (epoch_id);

-- DPO training epochs metadata
CREATE TABLE IF NOT EXISTS dpo_epochs (
    epoch_id        TEXT PRIMARY KEY,
    status          TEXT NOT NULL DEFAULT 'pending',
    initial_loss    REAL,
    final_loss      REAL,
    pair_count      INTEGER NOT NULL DEFAULT 0,
    dataset_path    TEXT,
    deployed        INTEGER NOT NULL DEFAULT 0,
    started_at      TEXT,
    completed_at    TEXT,
    metadata_json   TEXT DEFAULT '{}'
);

-- Flywheel state tracking
CREATE TABLE IF NOT EXISTS flywheel_state (
    key             TEXT PRIMARY KEY,
    value           TEXT NOT NULL,
    updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
"""


def initialize_production_db(db_path: Path) -> sqlite3.Connection:
    """
    Initialize the production log database with the full schema.
    Safe to call multiple times (idempotent).
    """
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    conn.executescript(PRODUCTION_LOG_SCHEMA)
    conn.commit()
    return conn


def get_production_db(db_path: Path) -> sqlite3.Connection:
    """
    Get a connection to an existing production log database.
    Automatically initializes the tables if not yet created.
    """
    return initialize_production_db(db_path)


def get_db_stats(db_path: Path) -> dict[str, int]:
    """Get aggregate log and pair counts from the database."""
    conn = get_production_db(db_path)
    try:
        total_logs = conn.execute("SELECT COUNT(*) as cnt FROM inference_logs").fetchone()["cnt"]
        pending_logs = conn.execute("SELECT COUNT(*) as cnt FROM inference_logs WHERE is_processed = 0").fetchone()["cnt"]
        processed_logs = total_logs - pending_logs
        total_pairs = conn.execute("SELECT COUNT(*) as cnt FROM preference_pairs").fetchone()["cnt"]
        total_epochs = conn.execute("SELECT COUNT(*) as cnt FROM dpo_epochs").fetchone()["cnt"]
        return {
            "total_logs": total_logs,
            "pending_logs": pending_logs,
            "processed_logs": processed_logs,
            "total_pairs": total_pairs,
            "total_epochs": total_epochs,
        }
    finally:
        conn.close()
